### ISSUE TITLE
Improve dataset page layout

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#10]
Put the categories and related items directly in the dataset page. @hoedic will work on the layout with the designer later but there are some technical aspects to work on: currently groups and related are in a different tab mainly to allow administrator to add them in a separate page.

The target  is mainly for the user to see everything in the same page. So for a non-admin the tabs for groups and related should not be visible and the information will be within the main dataset page. The admin should still be able to see the related and group tab in order to manage them.

**Comment by Hoedic** [comment]
@deniszgonjanin : there is a couple of issue with this

- Related: I am able to add an item, but it does not show up on the main dataset page and keeps saying "No related item). Below images when on the related tab and on the main dataset page.

![screenshot_58](https://cloud.githubusercontent.com/assets/510886/6377717/3e6c8ad8-bcf4-11e4-9123-b244e924e16a.png)

![screenshot_59](https://cloud.githubusercontent.com/assets/510886/6377719/43dd269e-bcf4-11e4-9128-b35e41113441.png)


- Group: When going to the "group" tab to add one, the button to add a group does not appear (although I am admin of the organization. 
![screenshot_57](https://cloud.githubusercontent.com/assets/510886/6377675/d1b8f99e-bcf3-11e4-9ee5-63edb65ed68c.png)

**Comment by deniszgonjanin** [comment]
@Hoedic Were you testing on staging? I'm sorry, I forgot to deploy there. I've deployed now, and everything seems to work for me fine. Can you take another look? eg. http://donneesqcsb.dcats.ca/dataset/casernes-incendie

If you were testing locally, the problem might have been that you need to update `ckan.plugins`. https://github.com/boxkite/donneesqc/blob/master/development.ini#L108

**Comment by Hoedic** [comment]
Yes, it was locally. I'll check later if the .ini was the issue. Indeed, it works well on staging.
