### ISSUE TITLE
Give access to integrate Drupal

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#2]
For next call (feb 17th) we will have to discuss how to install Drupal. 

I should be able to have some guide to do it. The question is who does it. Tasks to be done:
- Install Drupal (under which webserver? Which port? Which database -it's using postgres)
- Install extensions/modules needed 
- Configure the reverse proxy (nginx?)

**Comment by Hoedic** [comment]
Document what is needed to run Drupal

**Comment by deniszgonjanin** [comment]
@Hoedic when you get a chance, send us your public key
