### ISSUE TITLE
Index the organization name in the dataset

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#20]
Since there will be several similar datasets with the same name, it would be useful that putting the name of the organisation with the researched item put the result of that organization first.

Example: currently there are 2 datasets names "pistes cyclables", one for organization City of Montréal, one from Nord Ouvert.

If I search "Piste cyclable Montréal", the dataset from Montréal comes first (logical since the dataset has a tag "Montréal")

If I search "Piste cyclable Nord Ouvert" I don't even get any piste cyclable dataset.

We can expect that some people will use a very naive approach when searching data using something list "what-i-am-looking-for city-name". If adding the city name somehow excludes results because the organisation's name is mention nowhere else than at the organisation level, it's a issue.

It would be possible to ask organization to manually add the name of the organization either in the title, description or keyword, but chances are good that some will forget.

Option I see (besides the manual thing)
- Ask Solr to index the organization name (which does not seem to be the case when looking at the behaviour)
- Generate a tag that always add the organization name

**Comment by deniszgonjanin** [comment]
Adding the field to Solr might be the simplest solution, and the best since the primary concern is about free form text search. It also means the user doesn't need to do anything extra

**Comment by Hoedic** [comment]
Ok, so let's do that. I remove the label "to be discussed" and it should be considered as medium priority.

I guess it's mainly a quesiton of changing the schema (I really don't know SOLR that much), it should be fairly quick to do, right?

**Comment by deniszgonjanin** [comment]
I cannot seem to reproduce this. I always seem to get the correct result. I need to poke around and confirm, but I think the organization name might already be indexed for free-form search.

Do you have a data dump I could use to reproduce this issue? We should have a common set of data to test on anyway.

**Comment by Hoedic** [comment]
@deniszgonjanin: It's on the staging environment.

- Searching for the Montréal dataset (I do get the Montréal dataset first, probably because it contains a tag "Montreal" : http://donneesqcsb.dcats.ca/dataset?q=Piste+cyclable+Montr%C3%A9al&sort=score+desc%2C+metadata_modified+desc

- Searching for the Open North dataset: http://donneesqcsb.dcats.ca/dataset?q=Piste+cyclable+Nord+Ouvert&sort=score+desc%2C+metadata_modified+desc

In that case, the dataset "Pistes cyclables" (http://donneesqcsb.dcats.ca/dataset/pistes-cyclables-no) does not even appear.

**Comment by deniszgonjanin** [comment]
The owner organization is indeed indexed in Solr - you can find out what is in the Solr index by the way by executing an API package search call, like:
```
ckan.action.package_search(q='Piste cyclable')
```
I am not sure why the free-form query "Piste cyclable Nord Ouvert" doesn't return the proper dataset. My best guess is that Solr simply doesn't think that dataset is a proper match for that particular query. 

Solr attaches a relevance score to an item and returns results based on that. It doesn't simply return any query where all constituent words are in the index. So we need to find a way to increase the weight of the organization title with respect to dataset searches. I'll try a couple of things and see how it goes.

**Comment by Hoedic** [comment]
Ok. 

I did a couple more tests and for example if I use the search string `"Nord Ouvert" pistes cyclables` (with quotes), then the good data set comes out. I've done the test by adding one for city of Sherbrooke and adding searching `Pistes cyclables sherbrooke`and it's the first one to come out.

Sounds like CKAN has some difficulties to manage the organization name with multiple words. I guess most of the people will search the name of the data set plus just the name of the city (e.g Montreal, Québec, etc.) so the current behaviour sounds sufficient. We will investigate it if we really hear some complains about it.
