### ISSUE TITLE
Should Organization be required on dataset form

### ISSUE THREAD

**Issue by deniszgonjanin** [boxkite/ckanext-donneesqctheme#22]
By default no organization need be entered when creating a dataset. Should it be made required? Asking because it might impact how we approach #19, and I don't know if it makes sense to have datasets that do not belong to any of the stakeholders

cc/ @Hoedic

**Comment by Hoedic** [comment]
Good point. Yes, organization should be mandatory.

**Comment by deniszgonjanin** [comment]
Any objections to using ckanext-scheming to define dataset schemas? It's a lot more flexible and faster than implementing IDatasetForm the old way

**Comment by Hoedic** [comment]
No objection, I feel we will have to play with the schema so it's better to have a flexible tool.

**Comment by deniszgonjanin** [comment]
Organization is now mandatory, with a server-side validator
