### ISSUE TITLE
Automate "featured" view at the dataset level

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#27]
Currently the featured view displayed at the dataset level has to be determined manually by the user. As consequence is that most dataset might not have any view featured for the following reason:

1. In the context of DonneesQc, most of the people who will upload data will not be that familiar with the tool
2. Several of the main producers intend to automate the data flow (e.g harvesting), so nobody will go on the portal to add a view
3. For geospatial data, when done manually, the geojson file might not be available all the time (need to time generate the geojson from shp or kml) so the user won't be able to select the correct file.

Would it be possible to make it automatic: if not featured view exists for a dataset, if an existing format can be used for preview, use it. (That might be difficult to manage if we want to wait until the geojson is generated)

**Comment by deniszgonjanin** [comment]
@Hoedic great suggestion. Can you open this (or I can) on [ckanext-featuredviews]( https://github.com/deniszgonjanin/ckanext-featuredviews) so we can track it there, as the complete changes needed for this will live inside that extension and not ckanext-donneesqctheme.

If you have any other ideas or suggestions, feel free to discuss them there as well
