### ISSUE TITLE
Users to be member of all groups by default

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#32]
I don't know if this is new with 2.3, but it seems that now a user has to be member of a group to put datasts in that group.

In Données Québec, all users should be able to link datasets with all groups. Would it be possible to have the users linked with all the groups when created?

**Comment by Hoedic** [comment]
@deniszgonjanin : Here is the pull request that would solve the problem. It's milestoned for CKAN 2.4, maybe we could integrate it in our fork for the time being: https://github.com/ckan/ckan/pull/1665

**Comment by deniszgonjanin** [comment]
This should be working now. I've merged https://github.com/ckan/ckan/pull/1665 into our branch with a few changes. Seems to be working well, give it a go @Hoedic and close if everything is good.
