### ISSUE TITLE
Install extensions in Staging environment

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#4]
- Geospatial (query and medatada)
- Google analytics
- Hierarchical (to have a hierarchical structure of organizations)
- Disqus
- Qa

**Comment by deniszgonjanin** [comment]
@Hoedic this is done, except for `spatial` which we talked about elsewhere. I'll leave it open and you can close it if you want, or wait until there's a final verdict on `spatial`

We're making a couple of patches to datacats so you can run celery tasks in your dev environment, so I'll send you instructions tomorrow on how to run `qa` and `archiver` extensions in dev.

I also ran the `qa` on staging: http://donneesqcsb.dcats.ca/qa

**Comment by deniszgonjanin** [comment]
Also, we will eventually need a proper credentials for `googleanalytics` and `disqus` in the ini. Right now they're mocks

**Comment by Hoedic** [comment]
Closing. Spatial will have a whole different story. Yes, I will create credentials for disqus and GA. Some participants wanted to see if we can track the search terms in CKAN directly in GA which is normally possible, I just want to test it (except if you tell me you already did something like that)

**Comment by deniszgonjanin** [comment]
That should be possible with google analytics without any changes to CKAN. The search query is encoded in the url, so each search shows up in GA as a page load. So it's a matter of aggregating those there. It does require some skill with using GA

**Comment by Hoedic** [comment]
Yup, few week ago I found a help section in GA explaining how to do it. Just have to test it.
