### ISSUE TITLE
Contact / request dataset form

### ISSUE THREAD

**Issue by Hoedic** [boxkite/ckanext-donneesqctheme#5]
@hoedic to integrate existing "contact us" forms in the ckanext-donneesqctheme (first assignment)

@deniszgonjanin or @wardi to add function to pull list of list of organization (prerequisite on #6 )

**Comment by Hoedic** [comment]
Added existing code to the extension to add /suggest and /contact (created a plugin, a controller file and templates).

Assigning the issue to @deniszgonjanin to change how the mail is generated:
- In the form, add a drop down with a list of all organization (+ and option "All organizations" that should use a configuration email like what is already use `config.get('email_to')`)
- Pull the email addresses at the organization level to send the mail.

**Comment by deniszgonjanin** [comment]
@Hoedic this is all done, except we need to talk about how we want to actually send email. 

Do you want us to set up a generic SMTP server to send the messages, do you have one that you would like to use, or do you want to use a service like sendgrid?

**Comment by deniszgonjanin** [comment]
Going to close this an open a separate issue for the SMTP question
